In [2]:
pip install mnist

Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np
import mnist
import keras
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Flatten,Dense
from keras.utils import to_categorical

In [8]:
train_images=mnist.train_images()
train_labels=mnist.train_labels()
test_images=mnist.test_images()
test_labels=mnist.test_labels()

In [25]:
train_images

array([[[[-0.5],
         [-0.5],
         [-0.5],
         ...,
         [-0.5],
         [-0.5],
         [-0.5]],

        [[-0.5],
         [-0.5],
         [-0.5],
         ...,
         [-0.5],
         [-0.5],
         [-0.5]],

        [[-0.5],
         [-0.5],
         [-0.5],
         ...,
         [-0.5],
         [-0.5],
         [-0.5]],

        ...,

        [[-0.5],
         [-0.5],
         [-0.5],
         ...,
         [-0.5],
         [-0.5],
         [-0.5]],

        [[-0.5],
         [-0.5],
         [-0.5],
         ...,
         [-0.5],
         [-0.5],
         [-0.5]],

        [[-0.5],
         [-0.5],
         [-0.5],
         ...,
         [-0.5],
         [-0.5],
         [-0.5]]],


       [[[-0.5],
         [-0.5],
         [-0.5],
         ...,
         [-0.5],
         [-0.5],
         [-0.5]],

        [[-0.5],
         [-0.5],
         [-0.5],
         ...,
         [-0.5],
         [-0.5],
         [-0.5]],

        [[-0.5],
         [-0.5],
      

In [6]:
print(train_images.shape)

(60000, 28, 28)


In [7]:
print(test_images.shape)

(10000, 28, 28)


In [10]:
train_images=(train_images/255)-0.5
test_images=(test_images/255)-0.5
train_images=np.expand_dims(train_images,axis=3)
test_images=np.expand_dims(test_images,axis=3)


In [11]:
train_images.shape

(60000, 28, 28, 1)

In [12]:
num_classes=10
epochs=10
batch_size=128
num_filters=3
filter_size=3
pool_size=2

In [13]:
model=Sequential([Conv2D(num_filters,filter_size,input_shape=(28,28,1),activation='relu'),MaxPooling2D(pool_size=pool_size),Conv2D(num_filters,filter_size,activation='relu'),MaxPooling2D(pool_size=pool_size),Flatten(),Dense(10,activation='softmax')])

In [17]:
model.compile(loss=keras.losses.categorical_crossentropy,optimizer=keras.optimizers.SGD(lr=0.1),metrics=['accuracy'])
model.fit(train_images,to_categorical(train_labels),epochs=3,validation_data=(test_images,to_categorical(test_labels)))

Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 13s 215us/step - loss: 0.3189 - accuracy: 0.9015 - val_loss: 0.1458 - val_accuracy: 0.9548
Epoch 2/3
60000/60000 [==============================] - 12s 193us/step - loss: 0.1604 - accuracy: 0.9502 - val_loss: 0.1281 - val_accuracy: 0.9616
Epoch 3/3
60000/60000 [==============================] - 12s 194us/step - loss: 0.1410 - accuracy: 0.9567 - val_loss: 0.1143 - val_accuracy: 0.9654


In [20]:
print(to_categorical(test_labels))

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [21]:
predictions=model.predict(test_images[:5])
print(np.argmax(predictions,axis=1))

[7 2 1 0 4]


In [22]:
print(test_labels[:5])

[7 2 1 0 4]
